// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
// 
export const metadata = {
  title: "Yousra Abid | Full-Stack Developer (Laravel & ReactJS)",
  description:
    "Portfolio of Yousra Abid, a Full-Stack Developer specializing in Laravel, ReactJS, and scalable web applications. Explore projects, skills, and contact information.",
  keywords:
    "Yousra Abid, Full-Stack Developer, Laravel, ReactJS, Morocco Developer, Web Developer Portfolio",
  openGraph: {
    title: "Yousra Abid — Full-Stack Developer",
    description:
      "Building scalable, modern web applications using Laravel & ReactJS.",
    url: "https://yousra-abid.vercel.app",
    siteName: "Yousra.dev",
    images: [
      {
        url: "https://yousra-abid.vercel.app/og-image.jpg",
        width: 1200,
        height: 630,
        alt: "Yousra Abid Portfolio Preview",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    site: "@YousraDev", // optional if you have Twitter
  },
};

// 

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
